### ISSUE TITLE
Import (and any other batch operations) tracking

### ISSUE THREAD

**Issue by dpwrussell** [sorgerlab/minerva-infrastructure#32]
Add to the API the ability to get information about the status of an import (or other batch operation).

- [ ] Sync phase status
- [ ] Scan phase status
- [ ] Filesets extracted
- [ ] Filesets yet to be extracted
- [ ] Failed fileset extractions
- [ ] Overall status

It will probably be necessary to add some tracking information to the database (or other more temporary data store for operational data) in order to be able to query the AWS APIs needed to provide the necessary information. E.g. record the Execution ARN of step functions.
